[project]
name = "hiro-plot-utils"
version = "0.1.0"
description = "Some utilities for generating reproducible plots."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.5.2",
    "matplotlib>=3.10.7",
    "pyyaml>=6.0.3",
    "typing-extensions>=4.15.0",
]
